# Generated by Django 5.1.4 on 2026-02-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='The dispute description text')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('merchant_category', models.CharField(help_text='e.g., Software, Retail, Travel', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ANALYZED', 'Analyzed'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.CharField(help_text='Low, Medium, High', max_length=20)),
                ('classification', models.CharField(help_text='Dispute reason classification', max_length=100)),
                ('fraud_signals', models.JSONField(default=list, help_text='List of detected fraud indicators')),
                ('reasoning_steps', models.JSONField(default=list, help_text='Step-by-step reasoning logic')),
                ('recommended_action', models.CharField(help_text='Suggested next step', max_length=255)),
                ('financial_exposure', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='disputes.disputecase')),
            ],
        ),
    ]
